
version: "3"

services: 
  db:
    image: mysql:5.7
    container_name: main.mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: household
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    
    ports:
        - "7001:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /app
    volumes:
      - ./:/app
    environment: 
      MYSQL_HOST: db
      MYSQL_DATABASE: household
      MYSQL_USER: django
      MYSQL_PASSWORD: django
    ports:
      - "8000:8000"
    # depends on 옵션이 있어도, db가 먼저 실행되는 것을 보장할 수 없다. 
    depends_on:
      - db 

volumes:
  mysql-data: